In [10]:
!pip install faker

Requirement already satisfied: faker in /usr/local/lib/python3.10/dist-packages (19.10.0)
Requirement already satisfied: python-dateutil>=2.4 in /usr/local/lib/python3.10/dist-packages (from faker) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.4->faker) (1.16.0)

In [2]:
from faker import Faker

fake = Faker()

jumlah_data = 10

dummy_data = []

for _ in range(jumlah_data):
    nama = fake.name()
    nomor_telepon = fake.phone_number()
    alamat = fake.address()
    email = fake.email()

    data = f"Nama: {nama}\nNomor Telepon: {nomor_telepon}\nAlamat: {alamat}\nEmail: {email}\n"
    dummy_data.append(data)

file_name = "dummy_data.txt"
with open(file_name, "w") as file:
    for data in dummy_data:
        file.write(data + "\n")

print(f"{jumlah_data} data dummy telah disimpan dalam {file_name}.")

10 data dummy telah disimpan dalam dummy_data.txt.

In [3]:
file_path = "dummy_data.txt"

with open(file_path, "r") as file:

    text = file.read()

print(text)

Nama: Jimmy Arnold
Nomor Telepon: 001-643-816-6130x65676
Alamat: 165 Wayne Drive
Walkerton, MO 84717
Email: robert77@example.com

Nama: Tiffany Meyer
Nomor Telepon: 240-486-6286x392
Alamat: 9541 Sean Forks Apt. 790
Karaborough, MH 99263
Email: echan@example.org

Nama: Stephen Robinson
Nomor Telepon: (651)362-1860x65840
Alamat: 158 Rogers Club
Lake Laurenshire, AK 94438
Email: tristanflores@example.net

Nama: Dr. Eric Campbell
Nomor Telepon: (882)376-4268
Alamat: 568 Jones Ridges Apt. 020
Leeside, RI 72146
Email: harrisonthomas@example.net

Nama: Jason Campbell
Nomor Telepon: (965)263-3411
Alamat: 5391 Moreno Stravenue Apt. 441
West Wesleyside, NJ 81925
Email: johnsonraven@example.com

Nama: Kathleen Riley
Nomor Telepon: +1-951-540-8899
Alamat: 43502 Boone Plaza
Johnsonburgh, NH 04908
Email: ashlee29@example.net

Nama: Nicole David
Nomor Telepon: +1-636-948-7777x3472
Alamat: 189 Hoffman Locks
Monicaton, KY 87607
Email: kelly63@example.org

Nama: Karl Oconnell
Nomor Telepon: 001-326-342-2328x998
Alamat: 942 Amy Park
Nicholeport, OH 05144
Email: dbrowning@example.com

Nama: Susan Phillips
Nomor Telepon: 001-381-911-8444x57937
Alamat: 0822 Baker Drive Apt. 358
Hendricksburgh, LA 22215
Email: brandon06@example.net

Nama: Jennifer Jones
Nomor Telepon: 001-414-226-6860x237
Alamat: 2102 Charles Inlet Apt. 558
North Morgan, CA 57291
Email: jessicamiranda@example.org

In [4]:
import pandas as pd

In [5]:
import re

def extract_info(text):
    # Regex pattern
    name_pattern = r'Nama:\s(.*?)\n'
    phone_pattern = r'Nomor Telepon:\s(.*?)\n'
    address_pattern = r'Alamat:\s(.*?)\n'
    email_pattern = r'Email:\s(.*?)\n'
    email_name_pattern = r'Email:\s(.*?)@'
    #re.findall
    names = re.findall(name_pattern, text)
    phones = re.findall(phone_pattern, text)
    addresses = re.findall(address_pattern, text)
    emails = re.findall(email_pattern, text)
    email_names = re.findall(email_name_pattern, text)
    # Menghilangkan white space,- ,dll serta membuatnya dalam dictionary
    info_list = []
    for i in range(len(names)):
        info_dict = {
            "Name": names[i].strip(),
            "Phone": re.sub(r'\D', '', phones[i]).strip(),
            "Address": addresses[i].strip(),
            "Email": emails[i].strip(),
            "EmailName": email_names[i].strip(),
        }
        info_list.append(info_dict)

    return info_list


info_list = extract_info(text)

for info in info_list:
    print("Name:", info["Name"])
    print("Phone:", info["Phone"])
    print("Address:", info["Address"])
    print("Email:", info["Email"])
    print("Email Name:", info["EmailName"])
    print()

Name: Jimmy Arnold
Phone: 001643816613065676
Address: 165 Wayne Drive
Email: robert77@example.com
Email Name: robert77

Name: Tiffany Meyer
Phone: 2404866286392
Address: 9541 Sean Forks Apt. 790
Email: echan@example.org
Email Name: echan

Name: Stephen Robinson
Phone: 651362186065840
Address: 158 Rogers Club
Email: tristanflores@example.net
Email Name: tristanflores

Name: Dr. Eric Campbell
Phone: 8823764268
Address: 568 Jones Ridges Apt. 020
Email: harrisonthomas@example.net
Email Name: harrisonthomas

Name: Jason Campbell
Phone: 9652633411
Address: 5391 Moreno Stravenue Apt. 441
Email: johnsonraven@example.com
Email Name: johnsonraven

Name: Kathleen Riley
Phone: 19515408899
Address: 43502 Boone Plaza
Email: ashlee29@example.net
Email Name: ashlee29

Name: Nicole David
Phone: 163694877773472
Address: 189 Hoffman Locks
Email: kelly63@example.org
Email Name: kelly63

Name: Karl Oconnell
Phone: 0013263422328998
Address: 942 Amy Park
Email: dbrowning@example.com
Email Name: dbrowning

Name: Susan Phillips
Phone: 001381911844457937
Address: 0822 Baker Drive Apt. 358
Email: brandon06@example.net
Email Name: brandon06

Name: Jennifer Jones
Phone: 0014142266860237
Address: 2102 Charles Inlet Apt. 558
Email: jessicamiranda@example.org
Email Name: jessicamiranda

In [7]:
df =pd.DataFrame(info_list)
df

,Name,Phone,Address,Email,EmailName
0,Jimmy Arnold,001643816613065676,165 Wayne Drive,robert77@example.com,robert77
1,Tiffany Meyer,2404866286392,9541 Sean Forks Apt. 790,echan@example.org,echan
2,Stephen Robinson,651362186065840,158 Rogers Club,tristanflores@example.net,tristanflores
3,Dr. Eric Campbell,8823764268,568 Jones Ridges Apt. 020,harrisonthomas@example.net,harrisonthomas
4,Jason Campbell,9652633411,5391 Moreno Stravenue Apt. 441,johnsonraven@example.com,johnsonraven
5,Kathleen Riley,19515408899,43502 Boone Plaza,ashlee29@example.net,ashlee29
6,Nicole David,163694877773472,189 Hoffman Locks,kelly63@example.org,kelly63
7,Karl Oconnell,0013263422328998,942 Amy Park,dbrowning@example.com,dbrowning
8,Susan Phillips,001381911844457937,0822 Baker Drive Apt. 358,brandon06@example.net,brandon06
9,Jennifer Jones,0014142266860237,2102 Charles Inlet Apt. 558,jessicamiranda@example.org,jessicamiranda

In [11]:
df.to_csv('Laprak 2_NLP_Regex.csv')